/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as EducateRouteImport } from './routes/educate'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as ContractDetailAccountIdRouteImport } from './routes/contract-detail.$accountId'
import { Route as CalendarCallbackRouteImport } from './routes/calendar.callback'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
})
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
})
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
})
const EducateRoute = EducateRouteImport.update({
  id: '/educate',
  path: '/educate',
  getParentRoute: () => rootRouteImport,
})
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContractsRoute,
})
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
})
const ContractDetailAccountIdRoute = ContractDetailAccountIdRouteImport.update({
  id: '/contract-detail/$accountId',
  path: '/contract-detail/$accountId',
  getParentRoute: () => rootRouteImport,
})
const CalendarCallbackRoute = CalendarCallbackRouteImport.update({
  id: '/calendar/callback',
  path: '/calendar/callback',
  getParentRoute: () => rootRouteImport,
})
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
})

const ContractsRouteChildren = {
  ContractsIndexRoute: ContractsIndexRoute,
}

const ContractsRouteWithChildren = ContractsRoute._addFileChildren(
  ContractsRouteChildren,
)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractsRoute: ContractsRouteWithChildren,
  EducateRoute: EducateRoute,
  EscalationsRoute: EscalationsRoute,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  StrategyRoute: StrategyRoute,
  UsersRoute: UsersRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  CalendarCallbackRoute: CalendarCallbackRoute,
  ContractDetailAccountIdRoute: ContractDetailAccountIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
